// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEZsUpa0jMXn8MVmEU326rLV-D6VsCTA',
    appId: '1:146054379716:web:9ca1e94a386efbd6e17191',
    messagingSenderId: '146054379716',
    projectId: 'finora-2bf42',
    authDomain: 'finora-2bf42.firebaseapp.com',
    storageBucket: 'finora-2bf42.firebasestorage.app',
    measurementId: 'G-6J8CXFRG88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApa7piVQkeLo0vVmTAuodAmTcaV0wR2fI',
    appId: '1:146054379716:android:387515c0cf6dd36ee17191',
    messagingSenderId: '146054379716',
    projectId: 'finora-2bf42',
    storageBucket: 'finora-2bf42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfo0DlqZVrfeuK7vg6P1nUX4bnObkzuOw',
    appId: '1:146054379716:ios:a4fa7cd91886f02be17191',
    messagingSenderId: '146054379716',
    projectId: 'finora-2bf42',
    storageBucket: 'finora-2bf42.firebasestorage.app',
    iosBundleId: 'com.example.finoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfo0DlqZVrfeuK7vg6P1nUX4bnObkzuOw',
    appId: '1:146054379716:ios:a4fa7cd91886f02be17191',
    messagingSenderId: '146054379716',
    projectId: 'finora-2bf42',
    storageBucket: 'finora-2bf42.firebasestorage.app',
    iosBundleId: 'com.example.finoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEZsUpa0jMXn8MVmEU326rLV-D6VsCTA',
    appId: '1:146054379716:web:79cbe700fa44b473e17191',
    messagingSenderId: '146054379716',
    projectId: 'finora-2bf42',
    authDomain: 'finora-2bf42.firebaseapp.com',
    storageBucket: 'finora-2bf42.firebasestorage.app',
    measurementId: 'G-T5HMZD3RM8',
  );
}
